#!/usr/bin/ruby

require 'fileutils'

gem5home = Dir.new(Dir.pwd)
puts gem5home.path
specint_dir = (Dir.pwd+"/benchmarks/spec2k6bin/specint")
unless File.directory? File.expand_path(Dir.pwd+"/scriptgen")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/scriptgen")
end
unless File.directory? File.expand_path(Dir.pwd+"/results")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/results")
end
scriptgen_dir = Dir.new(Dir.pwd+"/scriptgen")

$specinvoke = { 
    "perlbench"  => "'#{specint_dir}/perlbench -I#{specint_dir}/perldepends -I#{specint_dir}/lib #{specint_dir} pack.pl'",
    "bzip2"      => "'#{specint_dir}/bzip2 #{specint_dir}/input.program 5'",
    "gcc"        => "'#{specint_dir}/gcc #{specint_dir}/cccp.in -o results/cccp.s'",
    "mcf"        => "'#{specint_dir}/mcf #{specint_dir}/inp.in'",
    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp < #{specint_dir}/capture.tst'",
    "hmmer"      => "'#{specint_dir}/hmmer --fixed 0 --mean 325 --num 45000 --sd 200 --seed 0 #{specint_dir}/bombesin.hmm'",
    "sjeng"      => "'#{specint_dir}/sjeng #{specint_dir}/test.txt'",
    "libquantum" => "'#{specint_dir}/libquantum 33 5'",
    "h264ref"    => "'#{specint_dir}/h264ref -d #{specint_dir}/foreman_test_encoder_baseline.cfg'",
    "omnetpp"    => "'#{specint_dir}/omnetpp #{specint_dir}/omnetpp.ini'",
    "astar"      => "'#{specint_dir}/astar #{specint_dir}/lake.cfg'",
    "Xalan"      => "'#{specint_dir}/Xalan -v #{specint_dir}/test.xml #{specint_dir}/xalanc.xsl'"  
}

$specint = [ 
    "perlbench",
    "bzip2",
    "gcc",
    "mcf",
    "gobmk",
    "hmmer",
    "sjeng",
    "libquantum",
    "h264ref",
    "omnetpp",
    "astar",
    "Xalan"  
]

$cpus = [ "detailed"]
$schemes = ["none", "tp", "ft"]
$cpus.each do |cpu|
    $schemes.each do |scheme|
        $specint.each do |p0file|
                script = File.new(scriptgen_dir.path+
                                  "/run_#{cpu}_#{scheme}_#{p0file}","w+")
                script.puts("#!/bin/bash")
                script.puts("build/ARM/gem5.fast configs/dramsim2/gen_trace.py \\")
                script.puts("    --cpu-type=#{cpu} \\")
                script.puts("    --caches \\")
                script.puts("    --maxinsts=$((10**7))\\")
                script.puts("    --dramsim2 \\")
                script.puts("    --devicecfg="+
                            "./ext/DRAMSim2/ini/DDR3_micron_16M_8B_x8_sg15.ini \\")
                script.puts("    --systemcfg="+
                            "./ext/DRAMSim2/system_#{scheme}.ini \\")
                script.puts("    --outputfile="+
                            "./results/#{cpu}_#{scheme}_#{p0file}.out \\")
                script.puts("    --gentrace \\")
                script.puts("    --tracefile="+
                            "./results/#{cpu}_#{scheme}_#{p0file}_p0 \\")
                script.puts("    --p0=#{$specinvoke[p0file]}")
                script.puts("    > results/stdout_#{cpu}_#{scheme}_#{p0file}.out")
                script_abspath = File.expand_path(script.path)
                script.close
                system "bash #{script_abspath}"
                system "rm #{script_abspath}"
        end
    end
end

