#!/usr/bin/ruby

$gem5home = Dir.new(Dir.pwd)

$experiments = %w[
    fa_detailed_libquantumtl6_libquantumtl6_libquantumtl6_c4MB
    fa_detailed_libquantumtl6_libquantumtl6_libquantumtl6_libquantumtl6_c4MB
    fa_detailed_mcftl6_libquantumtl6_libquantumtl6_c4MB
    fa_detailed_mcftl6_libquantumtl6_libquantumtl6_libquantumtl6_c4MB
    fa_timing_libquantumtl6_gcctl6_c4MB
    fa_timing_sjengtl6_astartl6_astartl6_c4MB
]

$experiments.each do |experiment|
    File.open(Dir.pwd+"/scriptgen/run_"+experiment) {|file|
        exp_abspath = File.expand_path file
        system "qsub -wd #{$gem5home.path} #{exp_abspath}"
    }
end
