#!/usr/bin/ruby

require 'tempfile'

ruby=`which ruby`
gem5home = Dir.new(Dir.pwd)
specint_dir = Dir.new(Dir.pwd+"/benchmarks/spec2k6bin/specint")
scriptgen_dir = Dir.new(Dir.pwd+"/scriptgen")

schemes = ["none","tp","ft"]
Dir.chdir(specint_dir)
schemes.each do |scheme|
    Dir.glob("*") do |p0file|
        Dir.glob("*") do |p1file|
            script = File.new(scriptgen_dir.to_path+"/run_#{scheme}_#{p0file}_#{p1file}","w")
            script.puts("#!/bin/bash
build/ARM/gem5.fast configs/dramsim2/dramsim2_se.py \\
    --cpu-type=timing \\
    --caches \\
    --dramsim2 \\
    --devicecfg=./ext/DRAMSim2/ini/DDR3_micron_16M_8B_x8_sg15.ini \\
    --systemcfg=./ext/DRAMSim2/system_#{scheme}.ini \\
    --outputfile=./results/#{scheme}_#{p0file}_#{p1file}.out \\
    --p0=#{p0file} \\
    --p1=#{p1file} \\
    > results/stdout_#{scheme}_#{p0file}_#{p1file}.out ")
            exec "qsub -cwd #{ruby} #{script}"
        end
    end
end

