#!/usr/bin/ruby

require 'fileutils'

$gem5home = Dir.new(Dir.pwd)
specint_dir = (Dir.pwd+"/benchmarks/spec2k6bin/specint")
unless File.directory? File.expand_path(Dir.pwd+"/scriptgen")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/scriptgen")
end
unless File.directory? File.expand_path(Dir.pwd+"/tl_results")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/tl_results")
end
$scriptgen_dir = Dir.new(Dir.pwd+"/scriptgen")

#Gem5 options
$fastforward = 10**9
$maxtinsts = 10**8
$maxtick = 2*10**15 
$cpus = %w[detailed timing]
$cacheSizes = [0,1,2,4]

#dramsim options
$device = "DDR3_micron_16M_8B_x8_sg15.ini"
$schemes = %w[tp none]
$turnlengths = [0] + (7..9).to_a

$specinvoke = { 
    #    "perlbench"  => "'#{specint_dir}/perlbench -I#{specint_dir}/perldepends -I#{specint_dir}/lib #{specint_dir} pack.pl'",
    "bzip2"      => "'#{specint_dir}/bzip2 #{specint_dir}/input.source 280'",
    "gcc"        => "'#{specint_dir}/gcc #{specint_dir}/200.in -o results/200.s'",
    "mcf"        => "'#{specint_dir}/mcf #{specint_dir}/inp.in'",
    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp --gtp-input #{specint_dir}/13x13.tst'",
    "hmmer"      => "'#{specint_dir}/hmmer #{specint_dir}/nph3.hmm #{specint_dir}/swiss41'",
    "sjeng"      => "'#{specint_dir}/sjeng #{specint_dir}/ref.txt'",
    "libquantum" => "'#{specint_dir}/libquantum 1397 8'",
    "h264ref"    => "'#{specint_dir}/h264ref -d #{specint_dir}/foreman_ref_encoder_baseline.cfg'",
    #    "omnetpp"    => "'#{specint_dir}/omnetpp #{specint_dir}/omnetpp.ini'",
    "astar"      => "'#{specint_dir}/astar #{specint_dir}/BigLakes2048.cfg'",
    "Xalan"      => "'#{specint_dir}/Xalan -v #{specint_dir}/t5.xml #{specint_dir}/xalanc.xsl'"  
}

$specint = $specinvoke.keys.sort

def sav_script( cpu, scheme, cacheSize, turnlength, p0, p1=nil, p2=nil, p3=nil ) 
    filename = "MEMINTENSITY_#{scheme}_#{cpu}_#{p0}"
    filename += "_#{p1}" unless p1.nil?
    filename += "_#{p2}" unless p2.nil?
    filename += "_#{p3}" unless p3.nil?
    filename += "_c#{cacheSize}MB_tl#{turnlength}"
    
    numpids  = 1
    numpids += 1 unless p1.nil?
    numpids += 1 unless p2.nil?
    numpids += 1 unless p3.nil?

    script = File.new($scriptgen_dir.path+"/run_#{filename}","w+")
    script.puts("#!/bin/bash")
    script.puts("build/ARM/gem5.fast \\")
    script.puts("    --stats-file=#{filename}_stats.txt \\")
    script.puts("    configs/dramsim2/dramsim2_se.py \\")
    script.puts("    --cpu-type=#{cpu} \\")
    script.puts("    --caches \\")
    script.puts("    --l2cache \\")
    unless cacheSize == 0
        script.puts("    --l3cache \\")
        script.puts("    --l3_size=#{cacheSize}MB\\")
    end
    script.puts("    --fast-forward=#{$fastforward} \\")
    script.puts("    --fixaddr\\") if scheme == "fa"
    script.puts("    --maxinsts=#{$maxtinsts} \\")
    script.puts("    --maxtick=#{$maxtick} \\")
    script.puts("    --dramsim2 \\")
    script.puts("    --tpturnlength=#{turnlength} \\") unless turnlength==0
    script.puts("    --devicecfg="+
                "./ext/DRAMSim2/ini/#{$device} \\")
    if turnlength == 0
        script.puts("    --systemcfg=./ext/DRAMSim2/system_ft.ini \\")
    else
        script.puts("    --systemcfg=./ext/DRAMSim2/system_#{scheme}.ini \\")
    end
    script.puts("    --outputfile=/dev/null \\")
    script.puts("    --numpids=#{numpids} \\")
    script.puts("    --p0=#{$specinvoke[p0]}\\")
    script.puts("    --p1=#{$specinvoke[p1]}\\") unless p1.nil?
    script.puts("    --p2=#{$specinvoke[p2]}\\") unless p2.nil?
    script.puts("    --p3=#{$specinvoke[p3]}\\") unless p3.nil?
    script.puts("    > results/stdout_#{filename}.out")
    script_abspath = File.expand_path(script.path)
    script.close
    system "qsub -wd #{$gem5home.path} #{script_abspath}"
end

Dir.chdir( specint_dir )
$cpus= %w[detailed]
$schemes=%w[none]
$cpus.product( $schemes,  $cacheSizes ).each do |cpu, scheme, cacheSize|
    $specint.each do|p0|
        sav_script( cpu, scheme, cacheSize, 6, p0 )
    end
end
