#!/usr/bin/ruby

require 'fileutils'

$gem5home = Dir.new(Dir.pwd)
puts $gem5home.path
specint_dir = (Dir.pwd+"/benchmarks/spec2k6bin/specint")
unless File.directory? File.expand_path(Dir.pwd+"/scriptgen")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/scriptgen")
end
unless File.directory? File.expand_path(Dir.pwd+"/results")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/results")
end
$scriptgen_dir = Dir.new(Dir.pwd+"/scriptgen")

#Gem5 options
$fastforward = 10**9
$maxtinsts = 10**8
$maxtick = 2*10**15 
$cpus = %w[detailed timing]
$cacheSizes = [0,1,2,4]

#dramsim options
$device = "DDR3_micron_16M_8B_x8_sg15.ini"
$schemes = %w[tp none]

#for running debug spec inputs
$specinvoke_test = { 
    #    "perlbench"  => "'#{specint_dir}/perlbench -I#{specint_dir}/perldepends -I#{specint_dir}/lib #{specint_dir} pack.pl'",
    "bzip2"      => "'#{specint_dir}/bzip2 #{specint_dir}/input.program 5'",
    "gcc"        => "'#{specint_dir}/gcc #{specint_dir}/cccp.in -o results/cccp.s'",
    "mcf"        => "'#{specint_dir}/mcf #{specint_dir}/inp.in'",
    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp < #{specint_dir}/capture.tst'",
    "hmmer"      => "'#{specint_dir}/hmmer --fixed 0 --mean 325 --num 45000 --sd 200 --seed 0 #{specint_dir}/bombesin.hmm'",
    "sjeng"      => "'#{specint_dir}/sjeng #{specint_dir}/test.txt'",
    "libquantum" => "'#{specint_dir}/libquantum 33 5'",
    "h264ref"    => "#{specint_dir}/h264ref -d #{specint_dir}/foreman_test_encoder_baseline.cfg'",
    #    "omnetpp"    => "'#{specint_dir}/omnetpp #{specint_dir}/omnetpp.ini'",
    "astar"      => "'#{specint_dir}/astar #{specint_dir}/lake.cfg'",
    "xalan"      => "'#{specint_dir}/Xalan -v #{specint_dir}/test.xml #{specint_dir}/xalanc.xsl'"  
}

#full spec inputs
$specinvoke = { 
    #    "perlbench"  => "'#{specint_dir}/perlbench -I#{specint_dir}/perldepends -I#{specint_dir}/lib #{specint_dir} pack.pl'",
    "bzip2"      => "'#{specint_dir}/bzip2 #{specint_dir}/input.source 280'",
    "gcc"        => "'#{specint_dir}/gcc #{specint_dir}/200.in -o results/200.s'",
    "mcf"        => "'#{specint_dir}/mcf #{specint_dir}/inp.in'",
    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp --gtp-input #{specint_dir}/13x13.tst'",
    "hmmer"      => "'#{specint_dir}/hmmer #{specint_dir}/nph3.hmm #{specint_dir}/swiss41'",
    "sjeng"      => "'#{specint_dir}/sjeng #{specint_dir}/ref.txt'",
    "libquantum" => "'#{specint_dir}/libquantum 1397 8'",
    "h264ref"    => "'#{specint_dir}/h264ref -d #{specint_dir}/foreman_ref_encoder_baseline.cfg'",
    #    "omnetpp"    => "'#{specint_dir}/omnetpp #{specint_dir}/omnetpp.ini'",
    "astar"      => "'#{specint_dir}/astar #{specint_dir}/BigLakes2048.cfg'",
    "xalan"      => "'#{specint_dir}/Xalan -v #{specint_dir}/t5.xml #{specint_dir}/xalanc.xsl'"  
}

$specint = $specinvoke.keys.sort

def sav_script( p0, p1, cpu, scheme, cacheSize )
    filename = "#{scheme}_#{cpu}_#{p0}_#{p1}_c#{cacheSize}MB"
    script = File.new($scriptgen_dir.path+
                      "/run_#{filename}","w+")
    script.puts("#!/bin/bash")
    script.puts("build/ARM/gem5.fast \\")
    script.puts("    --stats-file=#{filename}_stats.txt \\")
    script.puts("    configs/dramsim2/dramsim2_se.py \\")
    script.puts("    --cpu-type=#{cpu} \\")
    script.puts("    --caches \\")
    script.puts("    --l2cache \\")
    unless cacheSize == 0
        script.puts("    --l3cache \\")
        script.puts("    --l3_size=#{cacheSize}MB\\")
    end
    script.puts("    --fast-forward=#{$fastforward} \\")
    script.puts("    --fixaddr\\") if scheme == "fa"
    script.puts("    --maxinsts=#{$maxtinsts} \\")
    script.puts("    --maxtick=#{$maxtick} \\")
    script.puts("    --dramsim2 \\")
    script.puts("    --numpids=2 \\")
    script.puts("    --tpturnlength=6 \\")
    script.puts("    --devicecfg="+
                "./ext/DRAMSim2/ini/#{$device} \\")
    script.puts("    --systemcfg="+
                "./ext/DRAMSim2/system_#{scheme}.ini \\")
    script.puts("    --outputfile=/dev/null \\")
    script.puts("    --p0='#{$specinvoke[p0]}'\\")
    script.puts("    --p1='#{$specinvoke[p1]}'\\")
    script.puts("    > results/stdout_#{filename}.out")
    script_abspath = File.expand_path(script.path)
    script.close
    system "qsub -wd #{$gem5home.path} #{script_abspath}"
end

Dir.chdir( specint_dir )
$cpus.product( $schemes,  $cacheSizes ).each do |cpu, scheme, cacheSize|
    $specint.combination( 2 ).each do|p0, p1|
        sav_script( p0, p1, cpu, scheme, cacheSize )
    end
end
