#!/bin/bash

build/ARM/gem5.fast configs/dramsim2/dramsim2_se.py \
-c tests/test-progs/hello/bin/arm/linux/hello \
--cpu-type=timing \
--dramsim2 \
--devicecfg=./ext/DRAMSim2/ini/DDR3_micron_16M_8B_x8_sg15.ini \
--systemcfg=./ext/DRAMSim2/system.ini
