#!/usr/bin/ruby
require 'fileutils'

$gem5home = Dir.new(Dir.pwd)
puts $gem5home.path

$synthbench_dir = (Dir.pwd+"/tests/test-progs/test/arm/");

unless File.directory? File.expand_path(Dir.pwd+"/scriptgen")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/scriptgen")
end
unless File.directory? File.expand_path(Dir.pwd+"/results")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/results")
end
$scriptgen_dir = Dir.new(Dir.pwd+"/scriptgen")

#Gem5 options
$maxtinsts = 10**8
$maxtick = 2*10**15 
$cpus = [ "detailed", "timing"]
$cacheSizes = [0,1,2,4]
$p0periods = [96,128,192,256]

#dramsim options
$device = "DDR3_micron_16M_8B_x8_sg15.ini"
$schemes = %w[tp none fa]

#benchmark options
$duration = 60 * 10**6 #randmem duration in us
$periods = (0..2).map{|x| 10**x}  #in us

$tests = {
    "hardstride1" => "#{$synthbench_dir}hardstride -d #{$duration} -p 1",
    "randmem1"    => "#{$synthbench_dir}randmem -d #{$duration} -p 1",
    "randmem10"   => "#{$synthbench_dir}randmem -d #{$duration} -p 10",
    "randmem100"  => "#{$synthbench_dir}randmem -d #{$duration} -p 100",
    "nothing"     => "#{$synthbench_dir}nothing"
}

def sav_script( p0, tl0, p1, cpu, scheme, cacheSize )
    tl1 = 64
    filename = "#{scheme}_#{cpu}_#{p0}tl#{tl0}_#{p1}tl#{tl1}_c#{cacheSize}MB"
    script = File.new($scriptgen_dir.path+
                      "/run_#{filename}","w+")
    script.puts("#!/bin/bash")
    script.puts("build/ARM/gem5.fast \\")
    script.puts("    --stats-file=#{filename}_stats.txt \\")
    script.puts("    configs/dramsim2/dramsim2_se.py \\")
    script.puts("    --cpu-type=#{cpu} \\")
    script.puts("    --caches \\")
    script.puts("    --l2cache \\")
    unless cacheSize == 0
        script.puts("    --l3cache \\")
        script.puts("    --l3_size=#{cacheSize}MB\\")
    end
    script.puts("   --fixaddr\\") if scheme == "fa"
    script.puts("    --maxinsts=#{$maxtinsts} \\")
    script.puts("    --maxtick=#{$maxtick} \\")
    script.puts("    --dramsim2 \\")
    script.puts("    --numpids=2 \\")
    script.puts("    --tpturnlength=6 \\")
    script.puts("    --devicecfg="+
                "./ext/DRAMSim2/ini/#{$device} \\")
    script.puts("    --systemcfg="+
                "./ext/DRAMSim2/system_#{scheme}.ini \\")
    script.puts("    --outputfile=/dev/null \\")
    script.puts("    --p0='#{$tests[p0]}'\\")
    script.puts("    --p1='#{$tests[p1]}'\\")
    script.puts("    --diffperiod \\")
    script.puts("    --p0period=#{tl0} \\")
    script.puts("    --p1period=#{tl1} \\")
    script.puts("    > results/stdout_#{filename}.out")
    script_abspath = File.expand_path(script.path)
    script.close
    system "qsub -wd #{$gem5home.path} #{script_abspath}"
end

$cpus.product( $tests.keys, $p0periods, $tests.keys, $schemes, $cacheSizes ).
    each do |cpu, p0, tl0, p1, scheme, cacheSize|
    sav_script( p0, tl0, p1, cpu, scheme, cacheSize )
end
