#!/usr/bin/ruby

require 'fileutils'

gem5home = Dir.new(Dir.pwd)
puts gem5home.path
specint_dir = (Dir.pwd+"/benchmarks/spec2k6bin/specint")
unless File.directory? File.expand_path(Dir.pwd+"/scriptgen")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/scriptgen")
end
unless File.directory? File.expand_path(Dir.pwd+"/results")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/results")
end
scriptgen_dir = Dir.new(Dir.pwd+"/scriptgen")

$fastforward = 10**9
$maxtinsts = 10**8
$maxtick = 2*10**15 

$specinvoke_test = { 
    #    "perlbench"  => "'#{specint_dir}/perlbench -I#{specint_dir}/perldepends -I#{specint_dir}/lib #{specint_dir} pack.pl'",
    "bzip2"      => "'#{specint_dir}/bzip2 #{specint_dir}/input.program 5'",
    "gcc"        => "'#{specint_dir}/gcc #{specint_dir}/cccp.in -o results/cccp.s'",
    "mcf"        => "'#{specint_dir}/mcf #{specint_dir}/inp.in'",
    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp < #{specint_dir}/capture.tst'",
    "hmmer"      => "'#{specint_dir}/hmmer --fixed 0 --mean 325 --num 45000 --sd 200 --seed 0 #{specint_dir}/bombesin.hmm'",
    "sjeng"      => "'#{specint_dir}/sjeng #{specint_dir}/test.txt'",
    "libquantum" => "'#{specint_dir}/libquantum 33 5'",
    "h264ref"    => "#{specint_dir}/h264ref -d #{specint_dir}/foreman_test_encoder_baseline.cfg'",
    #    "omnetpp"    => "'#{specint_dir}/omnetpp #{specint_dir}/omnetpp.ini'",
    "astar"      => "'#{specint_dir}/astar #{specint_dir}/lake.cfg'",
    "Xalan"      => "'#{specint_dir}/Xalan -v #{specint_dir}/test.xml #{specint_dir}/xalanc.xsl'"  
}

$specinvoke = { 
    #    "perlbench"  => "'#{specint_dir}/perlbench -I#{specint_dir}/perldepends -I#{specint_dir}/lib #{specint_dir} pack.pl'",
    "bzip2"      => "'#{specint_dir}/bzip2 #{specint_dir}/input.source 280'",
    "gcc"        => "'#{specint_dir}/gcc #{specint_dir}/200.in -o results/200.s'",
    "mcf"        => "'#{specint_dir}/mcf #{specint_dir}/inp.in'",
    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp --gtp-input #{specint_dir}/13x13.tst'",
    "hmmer"      => "'#{specint_dir}/hmmer #{specint_dir}/nph3.hmm #{specint_dir}/swiss41'",
    "sjeng"      => "'#{specint_dir}/sjeng #{specint_dir}/ref.txt'",
    "libquantum" => "'#{specint_dir}/libquantum 1397 8'",
    "h264ref"    => "'#{specint_dir}/h264ref -d #{specint_dir}/foreman_ref_encoder_baseline.cfg'",
    #    "omnetpp"    => "'#{specint_dir}/omnetpp #{specint_dir}/omnetpp.ini'",
    "astar"      => "'#{specint_dir}/astar #{specint_dir}/BigLakes2048.cfg'",
    "Xalan"      => "'#{specint_dir}/Xalan -v #{specint_dir}/t5.xml #{specint_dir}/xalanc.xsl'"  
}

$specint = [ 
    #    "perlbench",
    "bzip2",
    "gcc",
    "mcf",
    "gobmk",
    "hmmer",
    "sjeng",
    "libquantum",
    "h264ref",
    #    "omnetpp",
    "astar",
    "Xalan"  
]

$cpus = [ "detailed", "timing"]
$schemes = ["tp","ft", "none", "open"]
Dir.chdir(specint_dir)
$cpus.each do |cpu|
    $schemes.each do |scheme|
        $specint.each do |p0file|
            $specint.each do |p1file|
                [0,1,2,4].each do |cacheSize|
                    filename = "#{scheme}_#{cpu}_#{p0file}_#{p1file}_c#{cacheSize}MB"
                    script = File.new(scriptgen_dir.path+
                                      "/run_#{filename}","w+")
                    script.puts("#!/bin/bash")
                    script.puts("/usr/bin/time -o #{filename}.time \\")
                    script.puts("build/ARM/gem5.fast \\")
                    script.puts("    --stats-file=#{filename}_stats.txt \\")
                    script.puts("    configs/dramsim2/dramsim2_se.py \\")
                    script.puts("    --cpu-type=#{cpu} \\")
                    script.puts("    --caches \\")
                    script.puts("    --l2cache \\")
                    unless cacheSize == 0
                        script.puts("    --l3cache \\")
                        script.puts("    --l3_size=#{cacheSize}MB\\")
                    end
                    script.puts("    --fast-forward=#{$fastforward} \\")
                    script.puts("    --maxinsts=#{$maxtinsts} \\")
                    script.puts("    --maxtick=#{$maxtick} \\")
                    script.puts("    --dramsim2 \\")
                    script.puts("    --tpturnlength=12 \\")
                    script.puts("    --devicecfg="+
                                "./ext/DRAMSim2/ini/DDR3_micron_16M_8B_x8_sg15.ini \\")
                    script.puts("    --systemcfg="+
                                "./ext/DRAMSim2/system_#{scheme}.ini \\")
                    #script.puts("    --outputfile=/dev/null \\") 
                    script.puts("    --outputfile="+
                                "/mnt/#{filename}.out \\")
                    script.puts("    --p0=#{$specinvoke[p0file]} \\")
                    script.puts("    --p1=#{$specinvoke[p1file]} \\")
                    script.puts("    > results/stdout_#{scheme}_#{cpu}_"+
                                "#{p0file}_#{p1file}_c#{cacheSize}MB.out")
                    script.puts("./parse_latencies.rb /mnt/#{filename}.out "+
                                "results/latency_t0_#{filename}.csv results/latency_t1_#{filename}.csv")
                    script.puts("rm /mnt/#{filename}.out")
                    script_abspath = File.expand_path(script.path)
                    script.close
                    #system "qsub -wd #{gem5home.path} #{script_abspath}"
                end
            end
        end
    end
end
