#!/bin/bash
./DRAMSim -s system.ini -c 30000 -S 4096 -d ini/DDR3_micron_64M_8B_x4_sg15.ini \
    -t traces/mase_art_MT_LOW.trc -r results/low.out &
./DRAMSim -s system.ini -c 30000 -S 4096 -d ini/DDR3_micron_64M_8B_x4_sg15.ini \
    -t traces/mase_art_MT_MEDIUM.trc -r results/med.out &
./DRAMSim -s system.ini -c 30000 -S 4096 -d ini/DDR3_micron_64M_8B_x4_sg15.ini \
    -t traces/mase_art_MT_HIGH.trc -r results/high.out

cat results/low.out  | grep "Thread: 0" > results/low_rt.out
cat results/med.out  | grep "Thread: 0" > results/med_rt.out
cat results/high.out | grep "Thread: 0" > results/high_rt.out

ruby get_delay_dist.rb results/low.out traces/mase_art_MT_LOW.trc \
    results/latencies.csv results/addressed_latencies.csv > results/mean.txt
