#!/usr/bin/ruby

require 'fileutils'

$gem5home = Dir.new(Dir.pwd)
puts $gem5home.path
specint_dir = (Dir.pwd+"/benchmarks/spec2k6bin/specint")
unless File.directory? File.expand_path(Dir.pwd+"/scriptgen")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/scriptgen")
end
unless File.directory? File.expand_path(Dir.pwd+"/results")
    FileUtils.mkdir_p File.expand_path(Dir.pwd+"/results")
end
$scriptgen_dir = Dir.new(Dir.pwd+"/scriptgen")

#Gem5 options
$fastforward = 10**9
$maxtinsts = 10**8
$maxtick = 2*10**15 
$cpus = %w[detailed timing]
$cacheSizes = [0,1,2,4]

#dramsim options
$device = "DDR3_micron_16M_8B_x8_sg15.ini"
$schemes = %w[tp none]

#other options
$inscount_hash_name = "inscount_hash"

#full spec inputs
$specinvoke = { 
    #    "perlbench"  => "'#{specint_dir}/perlbench -I#{specint_dir}/perldepends -I#{specint_dir}/lib #{specint_dir} pack.pl'",
    "bzip2"      => "'#{specint_dir}/bzip2 #{specint_dir}/input.source 280'",
    "gcc"        => "'#{specint_dir}/gcc #{specint_dir}/200.in -o results/200.s'",
    "mcf"        => "'#{specint_dir}/mcf #{specint_dir}/inp.in'",
    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp --gtp-input #{specint_dir}/13x13.tst'",
    "hmmer"      => "'#{specint_dir}/hmmer #{specint_dir}/nph3.hmm #{specint_dir}/swiss41'",
    "sjeng"      => "'#{specint_dir}/sjeng #{specint_dir}/ref.txt'",
    "libquantum" => "'#{specint_dir}/libquantum 1397 8'",
    "h264ref"    => "'#{specint_dir}/h264ref -d #{specint_dir}/foreman_ref_encoder_baseline.cfg'",
    #    "omnetpp"    => "'#{specint_dir}/omnetpp #{specint_dir}/omnetpp.ini'",
    "astar"      => "'#{specint_dir}/astar #{specint_dir}/BigLakes2048.cfg'",
    "xalan"      => "'#{specint_dir}/Xalan -v #{specint_dir}/t5.xml #{specint_dir}/xalanc.xsl'"  
}

# debug constants
#$fastforward = 10
#$maxinsts    = 10**5
#$cpus        = %w[timing]
#$cacheSizes  = [4]
#$schemes     = %w[none]
#$specinvoke = {
#    "gobmk"      => "'#{specint_dir}/gobmk --quiet --mode gtp --gtp-input #{specint_dir}/13x13.tst'",
#    "h264ref"    => "'#{specint_dir}/h264ref -d #{specint_dir}/foreman_ref_encoder_baseline.cfg'"
#}


$specint = $specinvoke.keys.sort

def get_filename( p0, cpu, scheme, cacheSize, inscount )
    "#{scheme}_#{cpu}_#{p0}_sp#{inscount}_c#{cacheSize}MB"
end

def sav_script( p0, cpu, scheme, cacheSize, inscount )
    filename = get_filename( p0, cpu, scheme, cacheSize, inscount )
    script = File.new($scriptgen_dir.path+
        "/run_#{filename}","w+")
    script.puts("#!/bin/bash")
    script.puts("build/ARM/gem5.fast \\")
    script.puts("    --stats-file=#{filename}_stats.txt \\")
    script.puts("    configs/dramsim2/dramsim2_se.py \\")
    script.puts("    --cpu-type=#{cpu} \\")
    script.puts("    --caches \\")
    script.puts("    --l2cache \\")
    unless cacheSize == 0
        script.puts("    --l3cache \\")
        script.puts("    --l3_size=#{cacheSize}MB\\")
    end
    script.puts("    --fast-forward=#{$fastforward} \\")
    script.puts("    --fixaddr\\") if scheme == "fa"
    script.puts("    --maxinsts=#{inscount} \\")
    script.puts("    --maxtick=#{$maxtick} \\")
    script.puts("    --dramsim2 \\")
    script.puts("    --numpids=1 \\")
    script.puts("    --tpturnlength=6 \\")
    script.puts("    --devicecfg="+
                "./ext/DRAMSim2/ini/#{$device} \\")
    script.puts("    --systemcfg="+
                "./ext/DRAMSim2/system_#{scheme}.ini \\")
    script.puts("    --outputfile=/dev/null \\")
    script.puts("    --p0=#{$specinvoke[p0]}\\")
    script.puts("    > results/stdout_#{filename}.out")
    script_abspath = File.expand_path(script.path)
    script.close
    system "qsub -wd #{$gem5home.path} #{script_abspath}"
end

inscounts = Marshal.load( File.read $inscount_hash_name )
puts inscounts
Dir.chdir( specint_dir )
exp_run = []
$cpus.product( $schemes,  $cacheSizes ).each do |cpu, scheme, cacheSize|
    $specint.combination( 2 ).each do|p0, p1|

        puts "#{scheme} #{cpu} #{cacheSize} #{p0} #{p1}"
        puts inscounts[scheme]
        puts inscounts[scheme][cpu]
        puts inscounts[scheme][cpu][cacheSize][p0]
        inscount = inscounts[scheme][cpu][cacheSize][p0][p1]

        curr_exp = get_filename( p0, cpu, scheme, cacheSize, inscount[0] )
        unless exp_run.include? curr_exp
            sav_script( p0, cpu, scheme, cacheSize, inscount[0] )
            exp_run << curr_exp
        end

        curr_exp = get_filename( p1, cpu, scheme, cacheSize, inscount[1] )
        unless exp_run.include? curr_exp
            sav_script( p1, cpu, scheme, cacheSize, inscount[1] )
            exp_run << curr_exp
        end

    end
end
