#!/usr/bin/ruby

require_relative 'runscripts'
require_relative 'unoptimized'
require_relative 'optimized'
require_relative 'scheduler'
require_relative 'synthetic'
require_relative 'security'
require_relative 'functionality'
include RunScripts

#------------------------------------------------------------------------------
# Security
#------------------------------------------------------------------------------
# cache_security

#------------------------------------------------------------------------------
# Unptimized Runs
#------------------------------------------------------------------------------
# single_benchmark
# cache_sweeping
# turn_length_sweeping
# thread_scaling

#------------------------------------------------------------------------------
# Optimized Runs
#------------------------------------------------------------------------------
# optimized_thread_scaling
# fa_thread_scaling


#------------------------------------------------------------------------------
# Scheduler Policy
#------------------------------------------------------------------------------
# fcfs_vs_frfcfs

#------------------------------------------------------------------------------
# Synthetic Benchmarks
#------------------------------------------------------------------------------
# synthetic_asym_period


#------------------------------------------------------------------------------
# Functionality
#------------------------------------------------------------------------------
test_sanity
