#!/usr/bin/ruby

require_relative 'runscripts'
require_relative 'security'
require_relative 'functionality'
require_relative 'performance'
require_relative 'memctl_unoptimized'
require_relative 'memctl_optimized'
require_relative 'memctl_scheduler'
require_relative 'memctl_synthetic'
include RunScripts

#------------------------------------------------------------------------------
# Security
#------------------------------------------------------------------------------
# cache_security
# execution_time_compare
# execution_time_compare_qsub
# security_debug
# paddr_test
# setpart_vs_private

#------------------------------------------------------------------------------
# Functionality
#------------------------------------------------------------------------------
# insecure_sanity
# insecure_deep
# secure_sanity
# secure_deep
# secure_scaling
# only_waypart
# only_mc
# only_l2l3
# only_membus

#------------------------------------------------------------------------------
# Performance
#------------------------------------------------------------------------------
# prelim_local
# scalability_local
# breakdown_local
# prelim_qsub
# scalability_qsub
# per_breakdown_qsub
# multicore_tc_qsub
# coordination_qsub
# coordination_local


###############################################################################
# Memory Controller Tests
###############################################################################
#------------------------------------------------------------------------------
# Unptimized Runs
#------------------------------------------------------------------------------
# single_benchmark
# cache_sweeping
# turn_length_sweeping
# thread_scaling

#------------------------------------------------------------------------------
# Optimized Runs
#------------------------------------------------------------------------------
# optimized_thread_scaling
# fa_thread_scaling

#------------------------------------------------------------------------------
# Scheduler Policy
#------------------------------------------------------------------------------
# fcfs_vs_frfcfs

#------------------------------------------------------------------------------
# Synthetic Benchmarks
#------------------------------------------------------------------------------
# synthetic_asym_period
